config/routes.rb
Rails.application.routes.draw do
  resources :batches
  resources :team_members do
    resources :social_profiles
  end
  resources :events do
    resources :event_images
  end
  resources :courses

  root 'welcome#index'

end

app/models/team_member.rb
class TeamMember < ActiveRecord::Base
  has_many :social_profiles
  has_and_belongs_to_many :batches
  has_attached_file :profile_pic, default_url: "/images/missing.png"
  validates_attachment_content_type :profile_pic, content_type: /\Aimage\/.*\z/

  def as_json(options)
    TeamMemberSerializer.new(self).as_json(root: false)
  end


end

app/controllers/team_members_controller.rb
class TeamMembersController < ApplicationController
  before_action :set_team_member, only: [:show, :edit, :update, :destroy]

  # GET /team_members
  # GET /team_members.json
  def index
    @team_members = TeamMember.all
    respond_to do |format|
      format.html {}
      format.json {

        members = @team_members
        data = Hash.new
        data["team_members"] = members
        return_success_response(data, "Request Successful", 200)
      }
    end
  end

  # GET /team_members/1
  # GET /team_members/1.json
  def show
    if (@team_member.blank?)
      return return_error_response('Team Member Not Found', 404)
    end
    respond_to do |format|
      format.html {}
      format.json {
        data = Hash.new
        data["team_member"] = @team_member
        return_success_response(data, "Request Successful", 200)
      }
    end
  end

  # GET /team_members/new
  def new
    @team_member = TeamMember.new
  end

  # GET /team_members/1/edit
  def edit
  end

  # POST /team_members
  # POST /team_members.json
  def create
    @team_member = TeamMember.new(team_member_params)

    respond_to do |format|
      if @team_member.save
        format.html { redirect_to @team_member, notice: 'Team member was successfully created.' }
        format.json { render :show, status: :created, location: @team_member }
      else
        format.html { render :new }
        format.json { render json: @team_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /team_members/1
  # PATCH/PUT /team_members/1.json
  def update
    respond_to do |format|
      if @team_member.update(team_member_params)
        format.html { redirect_to @team_member, notice: 'Team member was successfully updated.' }
        format.json { render :show, status: :ok, location: @team_member }
      else
        format.html { render :edit }
        format.json { render json: @team_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /team_members/1
  # DELETE /team_members/1.json
  def destroy
    @team_member.destroy
    respond_to do |format|
      format.html { redirect_to team_members_url, notice: 'Team member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team_member
      begin
       @team_member = TeamMember.find(params[:id])
      rescue Exception =>  e
        return return_error_response(e.exception.to_s,404)
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_member_params
      params.require(:team_member).permit(:name, :bio, :qualifications, :teaching_experience, :industry_experience, :profile_pic)
    end
end

app/helpers/team_members_helper.rb
module TeamMembersHelper
end

app/views/team_members/_form.html.erb
<%= form_for(@team_member) do |f| %>
  <% if @team_member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@team_member.errors.count, "error") %> prohibited this team_member from being saved:</h2>

      <ul>
      <% @team_member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :bio %><br>
    <%= f.text_field :bio %>
  </div>
  <div class="field">
    <%= f.label :qualifications %><br>
    <%= f.text_field :qualifications %>
  </div>
  <div class="field">
    <%= f.label :teaching_experience %><br>
    <%= f.text_field :teaching_experience %>
  </div>
  <div class="field">
    <%= f.label :industry_experience %><br>
    <%= f.text_field :industry_experience %>
  </div>

    <div class="field">
      <%= f.label :profile_pic %><br>
      <%= f.file_field :profile_pic %>
    </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/team_members/edit.html.erb
<h1>Editing Team Member</h1>

<%= render 'form' %>

<%= link_to 'Show', @team_member %> |
<%= link_to 'Back', team_members_path %>

app/views/team_members/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Team Members</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Bio</th>
      <th>Qualifications</th>
      <th>Teaching experience</th>
      <th>Industry experience</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @team_members.each do |team_member| %>
      <tr>
        <td><%= team_member.name %></td>
        <td><%= team_member.bio %></td>
        <td><%= team_member.qualifications %></td>
        <td><%= team_member.teaching_experience %></td>
        <td><%= team_member.industry_experience %></td>
        <td><%= link_to 'Show', team_member %></td>
        <td><%= link_to 'Edit', edit_team_member_path(team_member) %></td>
        <td><%= link_to 'Destroy', team_member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Team member', new_team_member_path %>

app/views/team_members/new.html.erb
<h1>New Team Member</h1>

<%= render 'form' %>

<%= link_to 'Back', team_members_path %>

app/views/team_members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @team_member.name %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @team_member.bio %>
</p>

<p>
  <strong>Qualifications:</strong>
  <%= @team_member.qualifications %>
</p>

<p>
  <strong>Teaching experience:</strong>
  <%= @team_member.teaching_experience %>
</p>

<p>
  <strong>Industry experience:</strong>
  <%= @team_member.industry_experience %>
</p>

<h2>Social Profiles</h2>
<% @team_member.social_profiles.each do |sp| %>
    <p>
      <b>Label:</b>
      <%= sp.label %>
    </p>

    <p>
      <b>Url:</b>
      <%= sp.url %>
    </p>

    <%= link_to 'Delete Profile', [sp.team_member, sp],
                :confirm => 'Are you sure?',
                :method => :delete %>
<% end %>

<h2>Add a Social Profile</h2>
<%= form_for([@team_member, @team_member.social_profiles.build]) do |sp| %>
    <div class="field">
      <%= sp.label :label %><br />
      <%= sp.text_field :label %>
    </div>
    <div class="field">
      <%= sp.label :url %><br />
      <%= sp.text_area :url %>
    </div>
    <div class="actions">
      <%= sp.submit %>
    </div>
<% end %>

<%= link_to 'Edit', edit_team_member_path(@team_member) %> |
<%= link_to 'Back', team_members_path %>