config/routes.rb
Rails.application.routes.draw do
  resources :batches
  resources :team_members do
    resources :social_profiles
  end
  resources :events do
    resources :event_images
  end
  resources :courses

  root 'welcome#index'

end

app/models/batch.rb
class Batch < ActiveRecord::Base
  belongs_to :course
  has_and_belongs_to_many :team_members

  enum status: [:open,:completed,:running]
  enum schedule: [:weekend, :weekdays]



  def as_json(options)
    BatchSerializer.new(self).as_json(root: false)
  end


end

app/controllers/batches_controller.rb
class BatchesController < ApplicationController
  before_action :set_batch, only: [:show, :edit, :update, :destroy]

  # GET /batches
  # GET /batches.json
  def index
    @batches = Batch.all
    respond_to do |format|
      format.html {}
      format.json {

        data = Hash.new
        data["batches"] = @batches
        return_success_response(data, "Request Successful", 200)
      }
    end
  end

  # GET /batches/1
  # GET /batches/1.json
  def show
    respond_to do |format|
      format.html {}
      format.json {

        data = Hash.new
        data["batch"] = @batch
        return_success_response(data, "Request Successful", 200)
      }
    end
  end

  # GET /batches/new
  def new
    @batch = Batch.new
  end

  # GET /batches/1/edit
  def edit
  end

  # POST /batches
  # POST /batches.json
  def create
    @batch = Batch.new(batch_params)
    team_member_ids = params[:team_member_ids]


    respond_to do |format|
      if @batch.save
        format.html { redirect_to @batch, notice: 'Batch was successfully created.' }
        format.json { render :show, status: :created, location: @batch }
      else
        format.html { render :new }
        format.json { render json: @batch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /batches/1
  # PATCH/PUT /batches/1.json
  def update
    respond_to do |format|
      if @batch.update(batch_params)
        format.html { redirect_to @batch, notice: 'Batch was successfully updated.' }
        format.json { render :show, status: :ok, location: @batch }
      else
        format.html { render :edit }
        format.json { render json: @batch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /batches/1
  # DELETE /batches/1.json
  def destroy
    @batch.destroy
    respond_to do |format|
      format.html { redirect_to batches_url, notice: 'Batch was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_batch
      begin
      @batch = Batch.find(params[:id])
      rescue Exception =>  e
        return return_error_response(e.exception.to_s,404)
      end

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def batch_params
      params.require(:batch).permit(:course_id, :name, :price, :start_date, :schedule, :strength, :status ,:team_member_ids => [])
    end
end

app/helpers/batches_helper.rb
module BatchesHelper
end

app/views/batches/_form.html.erb
<%= simple_form_for @batch do |f| %>
  <% if @batch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@batch.errors.count, "error") %> prohibited this batch from being saved:</h2>

      <ul>
      <% @batch.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.association :course, as: :select %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.input :schedule %>
  </div>
  <div class="field">
    <%= f.label :strength %><br>
    <%= f.number_field :strength %>
  </div>
  <div class="field">
    <%= f.input :status%>
  </div>
  <div class="field">
    <%= f.association :team_members, as: :select %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/batches/edit.html.erb
<h1>Editing Batch</h1>

<%= render 'form' %>

<%= link_to 'Show', @batch %> |
<%= link_to 'Back', batches_path %>

app/views/batches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Batches</h1>

<table>
  <thead>
    <tr>
      <th>Course</th>
      <th>Name</th>
      <th>Price</th>
      <th>Start date</th>
      <th>Schedule</th>
      <th>Strength</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @batches.each do |batch| %>
      <tr>
        <td><%= batch.course.name %></td>
        <td><%= batch.name %></td>
        <td><%= batch.price %></td>
        <td><%= batch.start_date %></td>
        <td><%= batch.schedule %></td>
        <td><%= batch.strength %></td>
        <td><%= batch.status %></td>
        <td><%= link_to 'Show', batch %></td>
        <td><%= link_to 'Edit', edit_batch_path(batch) %></td>
        <td><%= link_to 'Destroy', batch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Batch', new_batch_path %>

app/views/batches/new.html.erb
<h1>New Batch</h1>

<%= render 'form' %>

<%= link_to 'Back', batches_path %>

app/views/batches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Course:</strong>
  <%= @batch.course.name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @batch.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @batch.price %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @batch.start_date %>
</p>

<p>
  <strong>Schedule:</strong>
  <%= @batch.schedule %>
</p>

<p>
  <strong>Strength:</strong>
  <%= @batch.strength %>
</p>

<p>
  <strong>Status:</strong>
  <%= @batch.status %>
</p>

<h2>Instructors</h2>
<p></p>
<% @batch.team_members.each do |instructor| %>
    <%= instructor.name %><br>
<% end %>
</p>
<%= link_to 'Edit', edit_batch_path(@batch) %> |
<%= link_to 'Back', batches_path %>